default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("ARS_DATABASE_NAME") %>
  username: <%= ENV.fetch("ARS_DATABASE_USER") %>
  password: <%= ENV.fetch("ARS_DATABASE_PASSWORD") %>

test:
  <<: *default
  database: ars_test

production:
  <<: *default
  database: ars_production
  username: ars
  password: <%= ENV["ARS_DATABASE_PASSWORD"] %>
